const ACTIVITY_ACTIONS = [
  'AUTH_LOGIN',
  'CONTRIBUTOR_CREATED',
  'CONTRIBUTOR_UPDATED',
  'CONTRIBUTOR_ACTIVATED',
  'CONTRIBUTOR_DEACTIVATED',
  'JOB_CREATED',
  'JOB_UPDATED',
  'JOB_ASSIGNED',
  'JOB_CANCELLED',
  'SUBMISSION_CREATED',
  'SUBMISSION_SUBMITTED',
  'SUBMISSION_RESUBMITTED',
  'REVISION_REQUESTED',
  'SUBMISSION_APPROVED',
];

const ACTIVITY_ENTITY_TYPES = ['Job', 'Submission', 'Contributor', 'User'];

module.exports = {
  ACTIVITY_ACTIONS,
  ACTIVITY_ENTITY_TYPES,
};
