const SYSTEM_ROLES = ['ADMIN', 'CONTRIBUTOR'];

const CONTRIBUTOR_ROLES = ['QUESTION_CREATOR', 'SOLUTION_CREATOR', 'RESOURCE_CURATOR'];

const SUBJECTS = ['MATHEMATICS', 'PHYSICS', 'CHEMISTRY', 'BIOLOGY', 'ENGLISH'];

const VERIFICATION_STATUSES = ['PENDING', 'VERIFIED', 'REJECTED'];

module.exports = {
  SYSTEM_ROLES,
  CONTRIBUTOR_ROLES,
  SUBJECTS,
  VERIFICATION_STATUSES,
};
